const airportNames = {
    "SPC": { name: "La Palma Airport", city: "Santa Cruz", country: "Spain" },
    "LIS": { name: "Lisbon Humberto Delgado Airport", city: "Lisbon", country: "Portugal" },
    "ATH": { name: "Athens International Airport", city: "Athens", country: "Greece" },
    "AGP": { name: "Malaga-Costa del Sol Airport", city: "Malaga", country: "Spain" },
    "BCN": { name: "Barcelona-El Prat Airport", city: "Barcelona", country: "Spain" },
    "LPA": { name: "Gran Canaria Airport", city: "Las Palmas", country: "Spain" },
    "AOK": { name: "Karpathos Island National Airport", city: "Karpathos", country: "Greece" },
    "ALC": { name: "Alicante-Elche Airport", city: "Alicante", country: "Spain" },
    "RHO": { name: "Rhodes International Airport", city: "Rhodes", country: "Greece" },
    "FUE": { name: "Fuerteventura Airport", city: "Fuerteventura", country: "Spain" },
    "FAO": { name: "Faro Airport", city: "Faro", country: "Portugal" },
    "NBE": { name: "Enfidha-Hammamet International Airport", city: "Enfidha", country: "Tunisia" },
    "HER": { name: "Heraklion International Airport", city: "Heraklion", country: "Greece" },
    "CTA": { name: "Catania-Fontanarossa Airport", city: "Catania", country: "Italy" },
    "DLM": { name: "Dalaman Airport", city: "Dalaman", country: "Turkey" },
    "BJV": { name: "Milas-Bodrum Airport", city: "Bodrum", country: "Turkey" },
    "OPO": { name: "Francisco Sá Carneiro Airport", city: "Porto", country: "Portugal" },
    "NCE": { name: "Nice Côte d'Azur Airport", city: "Nice", country: "France" },
    "PFO": { name: "Paphos International Airport", city: "Paphos", country: "Cyprus" },
    "BRI": { name: "Bari Karol Wojtyła Airport", city: "Bari", country: "Italy" },
    "IBZ": { name: "Ibiza Airport", city: "Ibiza", country: "Spain" },
    "MJT": { name: "Mytilene International Airport", city: "Lesbos", country: "Greece" },
    "DSS": { name: "Blaise Diagne International Airport", city: "Dakar", country: "Senegal" },
    "SID": { name: "Amílcar Cabral International Airport", city: "Sal", country: "Cape Verde" },
    "ZTH": { name: "Zakynthos International Airport", city: "Zakynthos", country: "Greece" },
    "PDL": { name: "João Paulo II Airport", city: "Azores", country: "Portugal" },
    "TFS": { name: "Tenerife South Airport", city: "Tenerife", country: "Spain" },
    "RTM": { name: "Rotterdam The Hague Airport", city: "Rotterdam", country: "Netherlands" },
    "TBS": { name: "Tbilisi International Airport", city: "Tbilisi", country: "Georgia" },
    "KGS": { name: "Kos International Airport", city: "Kos", country: "Greece" },
    "KEF": { name: "Keflavik International Airport", city: "Reykjavik", country: "Iceland" },
    "PMI": { name: "Palma de Mallorca Airport", city: "Palma", country: "Spain" },
    "VLC": { name: "Valencia Airport", city: "Valencia", country: "Spain" },
    "VCP": { name: "Viracopos-Campinas International Airport", city: "Campinas", country: "Brazil" },
    "LHR": { name: "London Heathrow Airport", city: "London", country: "United Kingdom" },
    "LCA": { name: "Larnaca International Airport", city: "Larnaca", country: "Cyprus" },
    "SVQ": { name: "Seville Airport", city: "Seville", country: "Spain" },
    "RAK": { name: "Marrakesh Menara Airport", city: "Marrakesh", country: "Morocco" },
    "AYT": { name: "Antalya Airport", city: "Antalya", country: "Turkey" },
    "ADB": { name: "Izmir Adnan Menderes Airport", city: "Izmir", country: "Turkey" },
    "GRO": { name: "Girona-Costa Brava Airport", city: "Girona", country: "Spain" },
    "SPU": { name: "Split Airport", city: "Split", country: "Croatia" }
  };

export default airportNames;